[project]
name = "glpi-cli"
version = "0.1"
requires-python = ">= 3.12.1"
description = "GLPI CLI"
authors = [
  {name = "Juan Oitavén García", email = "juanoitgar@gmail.com"},
]
readme = "README.md"

[project.optional-dependencies]
tests = ["pytest"]

[project.scripts]
glpi = "glpi_cli.app:main"
